version: '3.8'

services:
  server:
    build:
      context: .
    image: myserver
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}              # 보통 'db'
      - DB_USER=${DB_USER}              # 일반 사용자명 (myuser)
      - DB_PASSWORD=${DB_PASSWORD}      # 일반 사용자 비밀번호
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}        # 'redis'
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: always
    command: npm run start

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}   # root 비밀번호
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}                     # 일반 사용자
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"                              # 외부 접속 허용 포트
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

volumes:
  dbdata:
